version: '2'
services:
  1hproject-app:
    image: 1hproject
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://1hproject-postgresql:5432/1HProject
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://1hproject-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://1hproject-elasticsearch:9200
    ports:
      - 8080:8080
  1hproject-postgresql:
    extends:
      file: postgresql.yml
      service: 1hproject-postgresql
  1hproject-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: 1hproject-elasticsearch
